# default prompt for all multi-choice benchmarks (e.g. mmlu)

system: ""

user: |-
    Answer the following multiple choice question.
    The last line of your response should be of the following format: 'Answer: $LETTER' (without quotes) where LETTER is one of A, B, C, D, E, F, G, H, I or J.

    Question: {question}

    A. {A}
    B. {B}
    C. {C}
    D. {D}
    E. {E}
    F. {F}
    G. {G}
    H. {H}
    I. {I}
    J. {J}

    Think step by step before answering.
